# Generated by Django 4.2 on 2024-03-01 12:09

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "public_id",
                    models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name="public id"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="created at")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="updated at")),
                ("deleted_at", models.DateTimeField(blank=True, null=True, verbose_name="deleted at")),
                ("name", models.CharField(max_length=225, verbose_name="name")),
                ("code", models.CharField(db_index=True, max_length=15, verbose_name="code")),
            ],
            options={
                "verbose_name": "Category",
                "verbose_name_plural": "Categories",
                "db_table": "categories",
            },
        ),
        migrations.CreateModel(
            name="City",
            fields=[
                (
                    "public_id",
                    models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name="public id"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="created at")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="updated at")),
                ("deleted_at", models.DateTimeField(blank=True, null=True, verbose_name="deleted at")),
                ("name", models.CharField(max_length=225, verbose_name="name")),
                ("code", models.CharField(db_index=True, max_length=15, verbose_name="code")),
            ],
            options={
                "verbose_name": "City",
                "verbose_name_plural": "Cities",
                "db_table": "cities",
            },
        ),
        migrations.CreateModel(
            name="Country",
            fields=[
                (
                    "public_id",
                    models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name="public id"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="created at")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="updated at")),
                ("deleted_at", models.DateTimeField(blank=True, null=True, verbose_name="deleted at")),
                ("name", models.CharField(max_length=225, verbose_name="name")),
                ("code", models.CharField(db_index=True, max_length=15, verbose_name="code")),
            ],
            options={
                "verbose_name": "Country",
                "verbose_name_plural": "Countries",
                "db_table": "countries",
            },
        ),
        migrations.CreateModel(
            name="Language",
            fields=[
                (
                    "public_id",
                    models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name="public id"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="created at")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="updated at")),
                ("deleted_at", models.DateTimeField(blank=True, null=True, verbose_name="deleted at")),
                ("name", models.CharField(max_length=225, verbose_name="name")),
                ("code", models.CharField(db_index=True, max_length=15, verbose_name="code")),
            ],
            options={
                "verbose_name": "Language",
                "verbose_name_plural": "Languages",
                "db_table": "languages",
            },
        ),
        migrations.CreateModel(
            name="State",
            fields=[
                (
                    "public_id",
                    models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name="public id"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="created at")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="updated at")),
                ("deleted_at", models.DateTimeField(blank=True, null=True, verbose_name="deleted at")),
                ("name", models.CharField(max_length=225, verbose_name="name")),
                ("code", models.CharField(db_index=True, max_length=15, verbose_name="code")),
                (
                    "country",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="states",
                        to="core.country",
                        verbose_name="country",
                    ),
                ),
            ],
            options={
                "verbose_name": "State",
                "verbose_name_plural": "States",
                "db_table": "states",
            },
        ),
    ]
