# Generated by Django 4.2 on 2024-02-17 12:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="code",
            field=models.CharField(db_index=True, max_length=15, verbose_name="code"),
        ),
        migrations.AlterField(
            model_name="city",
            name="code",
            field=models.CharField(db_index=True, max_length=15, verbose_name="code"),
        ),
        migrations.AlterField(
            model_name="country",
            name="code",
            field=models.CharField(db_index=True, max_length=15, verbose_name="code"),
        ),
        migrations.AlterField(
            model_name="language",
            name="code",
            field=models.CharField(db_index=True, max_length=15, verbose_name="code"),
        ),
        migrations.AlterField(
            model_name="state",
            name="code",
            field=models.CharField(db_index=True, max_length=15, verbose_name="code"),
        ),
        migrations.AddConstraint(
            model_name="category",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deleted_at__isnull", True)),
                fields=("code",),
                name="category_code_unique_constraint",
            ),
        ),
        migrations.AddConstraint(
            model_name="city",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deleted_at__isnull", True)), fields=("code",), name="city_code_unique_constraint"
            ),
        ),
        migrations.AddConstraint(
            model_name="country",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deleted_at__isnull", True)),
                fields=("code",),
                name="country_code_unique_constraint",
            ),
        ),
        migrations.AddConstraint(
            model_name="language",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deleted_at__isnull", True)),
                fields=("code",),
                name="language_code_unique_constraint",
            ),
        ),
        migrations.AddConstraint(
            model_name="state",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deleted_at__isnull", True)), fields=("code",), name="state_code_unique_constraint"
            ),
        ),
    ]
