# Generated by Django 4.2 on 2024-02-17 12:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gender",
            name="code",
            field=models.CharField(db_index=True, max_length=15, verbose_name="code"),
        ),
    ]
