# Generated by Django 4.2 on 2024-03-09 07:01

import uuid

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Place",
            fields=[
                (
                    "public_id",
                    models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name="public id"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="created at")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="updated at")),
                ("deleted_at", models.DateTimeField(blank=True, null=True, verbose_name="deleted at")),
                ("name", models.CharField(max_length=225, verbose_name="name")),
                ("code", models.CharField(db_index=True, max_length=15, verbose_name="code")),
                ("slug", models.SlugField(unique=True, verbose_name="slug")),
                ("address", models.TextField(blank=True, null=True, verbose_name="address")),
                ("description", models.TextField(null=True, verbose_name="description")),
                (
                    "visiting_fees",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name="visiting fees"),
                ),
                ("website", models.URLField(blank=True, verbose_name="website")),
                ("location", django.contrib.gis.db.models.fields.PointField(srid=4326)),
            ],
            options={
                "verbose_name": "Place",
                "verbose_name_plural": "Places",
                "db_table": "places",
            },
        ),
        migrations.CreateModel(
            name="PlaceCategory",
            fields=[
                (
                    "public_id",
                    models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name="public id"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="created at")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="updated at")),
                ("deleted_at", models.DateTimeField(blank=True, null=True, verbose_name="deleted at")),
            ],
            options={
                "verbose_name": "Place Category",
                "verbose_name_plural": "Place Categories",
                "db_table": "place_categories",
            },
        ),
        migrations.CreateModel(
            name="PlaceImage",
            fields=[
                (
                    "public_id",
                    models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name="public id"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="created at")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="updated at")),
                ("deleted_at", models.DateTimeField(blank=True, null=True, verbose_name="deleted at")),
                ("image", models.CharField(max_length=1000, verbose_name="image")),
            ],
            options={
                "verbose_name": "Place Image",
                "verbose_name_plural": "Place Images",
                "db_table": "place_images",
            },
        ),
    ]
